### ISSUE TITLE
Feature to schedule meetings

### ISSUE THREAD

**Issue by imakish** [nexmo-community/build-a-thing-video#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phazonoverload** [comment]
Hey! Could you please provide the information requested in the issue template. Thanks! 😄

**Comment by imakish** [comment]
I mean like , in zoom or google meet you can schedule meetings before the meeting starts. As a student, this feature is really useful to me . The teacher informs me about the meeting (with a link, password with time) the day before and i can be Ready. Instead of getting  the code just before class and missing part of the class.

**Comment by phazonoverload** [comment]
There is a PR template with some questions - in the top comment when you opened the PR. Can you fill in all of the sections please? 😃

**Comment by imakish** [comment]
> There is a PR template with some questions - in the top comment when you opened the PR. Can you fill in all of the sections please? 😃

Yeah i have filled it out now, i guess i missed it earlier😅. Thanks.
