### ISSUE TITLE
Add more features to chat

### ISSUE THREAD

**Issue by phazonoverload** [nexmo-community/build-a-thing-video#16]
**Is your feature request related to a problem? Please describe.**

The chat currently just shows text, not who sent it, and doesn't distinguish between the current user and others.

**Describe the solution you'd like**

Show a username next to each message. Reliant on #6.

**Comment by MaryJoStaebler** [comment]
Hey @phazonoverload I'd like to take on this issue but it looks like another issue needs to be resolved to make it happen.  Is the other issue being worked on?

**Comment by phazonoverload** [comment]
It is, but it's been 16 days without movement. Let me check-in with them and give them a day or so to respond before I'll deem it inactive and either pick it up myself, or suggest perhaps that you look at #6.

**Comment by MaryJoStaebler** [comment]
I'm up for #6 if needed.

**Comment by MaryJoStaebler** [comment]
I have this ready. Just finishing #4
