### ISSUE TITLE
Room locking

### ISSUE THREAD

**Issue by phazonoverload** [nexmo-community/build-a-thing-video#4]
* Room can be locked by participants
* People can still enter by providing a passphrase stored against the room

**Comment by AnshMishra2001** [comment]
Hey! I am new to open source. Can I work on this issue under your able guidance.

**Comment by phazonoverload** [comment]
Hi! I'm afraid I don't have much time for mentorship, but as a suggestion of approach:

- On session creation, store an additional boolean field `locked` and set it to false
- Provide a button in the room, and when pressed it updates the database `locked` field and a user-provided passphrase. 
- Also send a signal to other clients so their UI can show the update
- If a user tries to access a locked room ask them for the passphrase

This repository is part of a Twitch stream that I do every two weeks at 6PM UK time at <https://twitch.tv/vonagedevs>, so if you contribute I won't be reviewing PRs until I'm live with the next episode in two weeks time. 

I've also noticed that you've posted this exact same message on a load of issues. I think it's fair that you choose one to work on and I'll assign you to it. Once you open a PR I'll happily assign you to others! 

Let me know if you want me to assign you to this issue, or any of the others.

**Comment by MaryJoStaebler** [comment]
I'm tackling this and pretty sure I have it all ready.
