### ISSUE TITLE
Show usernames on video tiles

### ISSUE THREAD

**Issue by phazonoverload** [nexmo-community/build-a-thing-video#6]
https://tokbox.com/developer/guides/customize-ui/js/#stream_name

**Comment by avats-dev** [comment]
Hi @phazonoverload , I want to contribute. Can you guide me a bit in implementing this or any of the other issues? Thanks, let me know.

**Comment by phazonoverload** [comment]
Heya! This is a project that we work on during my Twitch stream 'Build a Thing', so everything that is here so far has been done [live](https://www.twitch.tv/videos/758478633). 

If you take a look at the link above (<https://tokbox.com/developer/guides/customize-ui/js/#stream_name>), you'll see how to add a name to a stream, and then directly below how to show that name in the UI. 

If you are still interested I will assign the issue to you. We'll be reviewing PRs live and it'd be great if you could join. The other October shows are 6PM UK-time on the 9th and 23rd at <https://twitch.tv/vonagedevs>.

**Comment by avats-dev** [comment]
Ok, let me take a look, I'll let you know. Thanks.

**Comment by phazonoverload** [comment]
I'll wait to hear back before assigning this to you 😄 

The basic steps will be:

* Gather the users' name. Probably through the form on `index.html` and pass it to `room.html` as a query parameter. 
* When initializing the publisher, add the name.
* Show the name on publishers and subscribers.

**Comment by priyanshupardhi** [comment]
Hey, @phazonoverload can I work on it

**Comment by phazonoverload** [comment]
I'll give @avats-dev until tomorrow morning to get back to me and if I don't hear back or they're not able to do it then I'll happily assign it to you, @priyanshupardhi

**Comment by phazonoverload** [comment]
Hey @priyanshupardhi - you're on! Going to assign this to you. Let me know if you have any questions.

**Comment by phazonoverload** [comment]
Heya, because I've not heard back I'm going to assign this to someone else 🙂

**Comment by MaryJoStaebler** [comment]
I'll take this!
