### ISSUE TITLE
Add styling

### ISSUE THREAD

**Issue by phazonoverload** [nexmo-community/build-a-thing-video#7]
Neither the index.html or room.html have any styling. Would be a nice issue for a web designer / front-end developer

**Comment by C-Zekeri** [comment]
Hi!
I'd love to work on this issue. Anything you'd like me to know?

**Comment by phazonoverload** [comment]
Hello! You are welcome to take this and thanks for offering.

This is a project that we're building on a Twitch stream, so we'll be reviewing PRs live and it'd be great if you could join. 

The other October shows are 6PM UK-time on the 9th and 23rd at https://twitch.tv/vonagedevs. 

Let me know if you have any questions, and have fun!

**Comment by C-Zekeri** [comment]
Alright, thank you!

**Comment by C-Zekeri** [comment]
Hi @phazonoverload. Finally got the project setup. Before I get to work proper, I'd like to know if you have any design guidelines/schemes already in place or its free rein?

**Comment by phazonoverload** [comment]
I'm happy to say you basically have free reign at this point! Keep an eye on accessibility in terms of font size and contrast, but otherwise go for it!

Over the next few weeks we may do more complex markup and as a result need some more styling, but I'm happy to split that into future issues

**Comment by C-Zekeri** [comment]
Great. Thank you.

**Comment by C-Zekeri** [comment]
Hi! @phazonoverload 
I just made a pull request concerning this issue:
https://github.com/nexmo-community/build-a-thing-video/pull/11#issue-498683274
